Args= --initialize-at-build-time=io.micronaut.opensearch.restclient.converter.StringToNodeSelectorConverter \
      --initialize-at-build-time=io.micronaut.opensearch.restclient.converter.StringToHttpHostConverter \
      --initialize-at-build-time=io.micronaut.opensearch.restclient.converter.StringToHeaderConverter
